ALTER TABLE USUARIO
ADD Estado bit NOT NULL;

-- Estado en 1 significa que está abierta la solicitud
ALTER TABLE SOLICITUD
ADD Estado bit NOT NULL DEFAULT 1;


ALTER TABLE COMENTARIO
ADD Comentario varchar(100) NOT NULL;

ALTER TABLE SOLICITUD
ADD CONSTRAINT FkLegajoS FOREIGN KEY (Legajo)
	REFERENCES USUARIO(Legajo);

ALTER TABLE SOLICITUD
ADD CONSTRAINT FkTipificacionS FOREIGN KEY (IdTipificacion)
	REFERENCES TIPIFICACION(IdTipificacion);

ALTER TABLE COMENTARIO
ADD CONSTRAINT FkIncidenciaC FOREIGN KEY (IdIncidencia)
	REFERENCES SOLICITUD(IdIncidencia);

ALTER TABLE COMENTARIO
ADD CONSTRAINT FkLegajoC FOREIGN KEY (Legajo)
	REFERENCES USUARIO(Legajo);

ALTER TABLE USUARIO
ADD CONSTRAINT FkUbicacionU FOREIGN KEY (IdUbicacion)
	REFERENCES UBICACION(IdUbicacion);

ALTER TABLE USUARIO
ADD CONSTRAINT FkDepartamentoU FOREIGN KEY (IdDepartamento)
	REFERENCES DEPARTAMENTO(IdDepartamento);

ALTER TABLE DERIVACION
ADD CONSTRAINT FkIdIncidenciaD FOREIGN KEY (IdIncidencia)
	REFERENCES SOLICITUD(IdIncidencia);

ALTER TABLE SOLICITUD
ADD IdArea int NOT NULL;

ALTER TABLE SOLICITUD
ADD CONSTRAINT FkIdAreaS FOREIGN KEY (IdArea)
	REFERENCES AREA(IdArea);

ALTER TABLE DERIVACION
ADD IdOrigen int NOT NULL;

ALTER TABLE DERIVACION
ADD IdDestino int NOT NULL;

ALTER TABLE DERIVACION
ADD CONSTRAINT FkOrigenD FOREIGN KEY (IdOrigen)
	REFERENCES AREA(IdArea);


ALTER TABLE DERIVACION
ADD CONSTRAINT FkDestinoD FOREIGN KEY (IdDestino)
	REFERENCES AREA(IdArea);

ALTER TABLE TIPIFICACION
ADD CONSTRAINT FkHeredaDe FOREIGN KEY (HeredaDe)
	REFERENCES TIPIFICACION(IdTipificacion)
